import type { Config } from "tailwindcss";

export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
  ],
  theme: {
    extend: {
      colors: {
        // M3 Color Tokens (既存のまま)
        "m3-primary": "#6750A4",
        "m3-on-primary": "#FFFFFF",
        "m3-primary-container": "#EADDFF",
        "m3-on-primary-container": "#21005D",
        "m3-secondary": "#625B71",
        "m3-on-secondary": "#FFFFFF",
        "m3-secondary-container": "#E8DEF8",
        "m3-on-secondary-container": "#1D192B",
        "m3-tertiary": "#7D5260",
        "m3-on-tertiary": "#FFFFFF",
        "m3-tertiary-container": "#FFD8E4",
        "m3-on-tertiary-container": "#31111D",
        "m3-error": "#B3261E",
        "m3-on-error": "#FFFFFF",
        "m3-error-container": "#F9DEDC",
        "m3-on-error-container": "#410E0B",
        "m3-background": "#FEF7FF",
        "m3-on-background": "#1D1B20",
        "m3-surface": "#FEF7FF",
        "m3-on-surface": "#1D1B20",
        "m3-surface-variant": "#E7E0EC",
        "m3-on-surface-variant": "#49454F",
        "m3-surface-container-lowest": "#FFFFFF",
        "m3-surface-container-low": "#F7F2FA",
        "m3-surface-container": "#F3EDF7",
        "m3-surface-container-high": "#ECE6F0",
        "m3-surface-container-highest": "#E6E0E9",
        "m3-outline": "#79747E",
        "m3-outline-variant": "#CAC4D0",
        "m3-state-hover": "rgba(103, 80, 164, 0.08)",
        "m3-state-focus": "rgba(103, 80, 164, 0.12)",
        "m3-state-pressed": "rgba(103, 80, 164, 0.12)",
      },
      borderRadius: {
        card: "24px",
        fab: "16px",
        "dialog-t": "28px",
        chip: "8px",
      },
      fontSize: {
        "display-large": ["57px", { lineHeight: "64px", fontWeight: "400" }],
        "display-medium": ["45px", { lineHeight: "52px", fontWeight: "400" }],
        "display-small": ["36px", { lineHeight: "44px", fontWeight: "400" }],
        "headline-large": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "headline-medium": ["28px", { lineHeight: "36px", fontWeight: "400" }],
        "headline-small": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "title-large": ["22px", { lineHeight: "28px", fontWeight: "400" }],
        "title-medium": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "title-small": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-large": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-medium": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-small": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-large": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-medium": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-small": ["11px", { lineHeight: "16px", fontWeight: "500" }],
      },
      fontFamily: {
        roboto: ["Roboto", "sans-serif"],
      },
      boxShadow: {
        // M3 Elevation levels
        'm3-0': 'none',
        'm3-1': '0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)',
        'm3-2': '0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)',
        'm3-3': '0px 1px 3px 0px rgba(0, 0, 0, 0.3), 0px 4px 8px 3px rgba(0, 0, 0, 0.15)',
        'm3-4': '0px 2px 3px 0px rgba(0, 0, 0, 0.3), 0px 6px 10px 4px rgba(0, 0, 0, 0.15)',
        'm3-5': '0px 4px 4px 0px rgba(0, 0, 0, 0.3), 0px 8px 12px 6px rgba(0, 0, 0, 0.15)',
      },
      typography: (theme: any) => ({
        m3: {
          css: {
            '--tw-prose-body': theme('colors.m3-on-surface-variant'),
            '--tw-prose-headings': theme('colors.m3-on-surface'),
            '--tw-prose-links': theme('colors.m3-primary'),
            '--tw-prose-bold': theme('colors.m3-on-surface'),
            '--tw-prose-code': theme('colors.m3-primary'),
            color: 'var(--tw-prose-body)',
            maxWidth: 'none',
            h1: { color: 'var(--tw-prose-headings)', fontSize: '32px', lineHeight: '40px', fontWeight: '500', marginTop: '2rem', marginBottom: '1rem' },
            h2: { color: 'var(--tw-prose-headings)', fontSize: '28px', lineHeight: '36px', fontWeight: '500', marginTop: '2rem', marginBottom: '0.75rem', paddingBottom: '0.5rem', borderBottom: `1px solid ${theme('colors.m3-outline-variant')}` },
            h3: { color: 'var(--tw-prose-headings)', fontSize: '20px', lineHeight: '28px', fontWeight: '500', marginTop: '1.5rem', marginBottom: '0.5rem' },
            h4: { color: 'var(--tw-prose-headings)', fontSize: '18px', lineHeight: '24px', fontWeight: '600', marginTop: '1rem', marginBottom: '0.5rem' },
            p: { fontSize: '14px', lineHeight: '20px', marginBottom: '1rem' },
            a: { color: 'var(--tw-prose-links)', textDecoration: 'none', fontWeight: '500', '&:hover': { textDecoration: 'underline' } },
            strong: { color: 'var(--tw-prose-bold)', fontWeight: '600' },
            code: { color: 'var(--tw-prose-code)', backgroundColor: theme('colors.m3-primary-container') + '4D', padding: '0.125rem 0.375rem', borderRadius: '0.25rem', fontSize: '0.875rem', '&::before': { content: '""' }, '&::after': { content: '""' } },
            pre: { backgroundColor: theme('colors.m3-surface-container-high'), border: `1px solid ${theme('colors.m3-outline-variant')}`, borderRadius: '0.5rem', padding: '1rem' },
            blockquote: { borderLeftWidth: '4px', borderLeftColor: theme('colors.m3-primary'), paddingLeft: '1rem', fontStyle: 'italic' },
            ul: { listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1rem' },
            ol: { listStyleType: 'decimal', paddingLeft: '1.5rem', marginBottom: '1rem' },
            li: { fontSize: '14px', lineHeight: '1.2', marginBottom: '0.125rem' },
            table: { width: '100%', borderCollapse: 'collapse', marginTop: '1.5rem', marginBottom: '1.5rem' },
            thead: { borderBottomWidth: '2px', borderBottomColor: theme('colors.m3-outline') },
            th: { textAlign: 'left', padding: '0.5rem', fontSize: '12px', fontWeight: '500', backgroundColor: theme('colors.m3-surface-container') },
            td: { padding: '0.5rem', borderBottom: `1px solid ${theme('colors.m3-outline-variant')}`, fontSize: '12px' },
            'tbody tr': { '&:hover': { backgroundColor: theme('colors.m3-surface-container') + '80' } },
            img: { borderRadius: '0.5rem', boxShadow: theme('boxShadow.m3-2'), marginTop: '1.5rem', marginBottom: '1.5rem', cursor: 'pointer', transition: 'transform 0.2s ease-out, box-shadow 0.2s ease-out', '&:hover': { transform: 'scale(1.02)', boxShadow: theme('boxShadow.m3-3') } },
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
} satisfies Config;
